version: "3"

services:
  db:
    image: postgres:15.2
    environment:
      - POSTGRES_DB=meme-manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/data/postgres
      - PGPORT=2139
    networks:
      - private
    ports:
      - "2139:2139"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure
  api:
    build:
      context: backend
      dockerfile: Api.Dockerfile.dev
    volumes:
      - "./backend/src:/app/src"
    ports:
      - "2137:2137"
    networks:
      - private
    depends_on:
      - db
    env_file:
      - backend.example.env
  frontend:
    build:
      context: frontend
      dockerfile: Frontend.Dockerfile.dev
    volumes:
      - "./frontend:/app"
    networks:
      - private
    ports:
      - "2138:2138"
    depends_on:
      - api
    environment:
      - WATCHPACK_POLLING=true
networks:
  private: