version: "3"

services:
  db:
    image: postgres:15.2
    environment:
      - POSTGRES_DB=meme-manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGPORT=2139
    networks:
      - private
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure
  api:
    build:
      context: backend
      dockerfile: Api.Dockerfile.production
    hostname: meme-api
    ports:
      - "21378:2137"
    volumes:
      - "./backend/logs:/app/build/logs"
      - "./backend/memes:/app/build/memes"
    networks:
      - private
    depends_on:
      - db
    env_file:
      - backend.example.env
  frontend:
    build:
      context: frontend
      dockerfile: Frontend.Dockerfile.production
    ports:
      - "80:80"
    networks:
      - private
    depends_on:
      - api
networks:
  private:
volumes:
  db-data: