version: "3"

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=meme-manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - private
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure
  api:
    build:
      context: backend
      dockerfile: Api.Dockerfile.dev
    volumes:
      - ./backend/src:/app/src
    ports:
      - "3070:3070"
    networks:
      - private
    depends_on:
      - db
    environment:
      - POSTGRES_DB=meme-manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
  frontend:
    build:
      context: frontend
      dockerfile: Frontend.Dockerfile.dev
    volumes:
      - "./frontend:/app"
    ports:
      - "3000:3000"
    networks:
      - private
    depends_on:
      - api
    environment:
       - WATCHPACK_POLLING=true
networks:
  private: