version: "3"

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=meme-manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - private
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure
  api:
    build:
      context: backend
      dockerfile: Api.Dockerfile.production
    ports:
      - "8000:8000"
    networks:
      - private
    depends_on:
      - db
    environment:
      - POSTGRES_DB=meme-manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
  frontend:
    build:
      context: frontend
      dockerfile: Frontend.Dockerfile.production
    ports:
      - "80:80"
    networks:
      - private
    depends_on:
      - api
    environment:
       - WATCHPACK_POLLING=true
networks:
  private: