version: "3"

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=meme-manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - private
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: on-failure
  api:
    build:
      context: backend
      dockerfile: Api.Dockerfile.production
    ports:
      - "3070:3070"
    volumes:
      - "./backend/logs:/app/build/logs"
      - "./backend/memes:/app/build/memes"
    networks:
      - private
    depends_on:
      - db
    environment:
      - NODE_ENV=production
    env_file:
      - backend.example.env
  frontend:
    build:
      context: frontend
      dockerfile: Frontend.Dockerfile.production
      args:
        - "REACT_APP_API_ADDRESS=http://localhost:3070/api"
    ports:
      - "80:80"
    networks:
      - private
    depends_on:
      - api
    env_file:
      - frontend.example.env
networks:
  private: